-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 15:29:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema user_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_schema` DEFAULT CHARACTER SET utf8 ;
USE `user_schema` ;

-- -----------------------------------------------------
-- Table `user_schema`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_schema`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_schema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_schema`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `edited_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
